-- 24520602 -- Nguyễn Duy Hưng

-- Mật khẩu: 12345@789

CREATE DATABASE THUCHANH

USE THUCHANH

CREATE TABLE SACH (
	MaSach CHAR(5) PRIMARY KEY,
	TenSach NVARCHAR(100),
	TheLoai NVARCHAR(30),
	DonGia MONEY,
	SoLuong INT
)

CREATE TABLE TACGIA (
	MaTG CHAR(5) PRIMARY KEY,
	HoTen NVARCHAR(50),
	QuocTich NVARCHAR(30),
	NgaySinh SMALLDATETIME,
	DienThoai VARCHAR(15)
)

CREATE TABLE TACGIA_SACH (
	MaTG CHAR(5) FOREIGN KEY REFERENCES TACGIA(MaTG),
	MaSach CHAR(5) FOREIGN KEY REFERENCES SACH(MaSach),
	PRIMARY KEY (MaTG, MaSach)
)

CREATE TABLE DOCGIA (
	MaDG CHAR(5) PRIMARY KEY,
	TenDG NVARCHAR(50),
	DiaChi NVARCHAR(50),
	NgaySinh SMALLDATETIME,
	DienThoai VARCHAR(15),
	NgDK SMALLDATETIME
)

CREATE TABLE PHATHANH (
	MaPH CHAR(5) PRIMARY KEY,
	MaSach CHAR(5) FOREIGN KEY REFERENCES SACH(MaSACH),
	NgayPH SMALLDATETIME,
	SoLuong INT,
	NXB NVARCHAR(100),
	LanPhatHanh INT
)

CREATE TABLE MUONSACH (
	MaMuon CHAR(5) PRIMARY KEY,
	MaDG CHAR(5) FOREIGN KEY REFERENCES DOCGIA(MaDG),
	MaSach CHAR(5) FOREIGN KEY REFERENCES SACH(MaSach),
	NgayMuon SMALLDATETIME,
	NgayTr SMALLDATETIME,
	TrangThai NVARCHAR(2)
)

-- Cau 2
GO
CREATE TRIGGER INSERT_UPDATE_PHATHANH
ON PHATHANH
AFTER INSERT, UPDATE
AS
BEGIN
	IF NOT UPDATE(MaSach) AND NOT UPDATE(NgayPH)
		RETURN
	IF EXISTS (SELECT I.MaPH
		FROM INSERTED I
		JOIN TACGIA_SACH TS ON TS.MaSach = I.MaSach
		JOIN TACGIA TG ON TG.MaTG = TS.MaTG
		WHERE I.NgayPH <= TG.NgaySinh)
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR (N'ERROR', 16, 1)
	END
END

-- Cau 3
ALTER TABLE PHATHANH ADD CONSTRAINT CHECK_SOLUONG CHECK(SOLUONG >= 500)

-- Cau 4
SELECT DG.MaDG, DG.TenDG
FROM DOCGIA DG
JOIN MUONSACH MS ON DG.MaDG = MS.MaDG
WHERE MS.NgayMuon = '2024-12-10'

-- Cau 5
SELECT TG.MaTG, TG.HoTen
FROM TACGIA TG
JOIN TACGIA_SACH TS ON TG.MaTG = TS.MaTG
JOIN SACH S ON S.MaSach = TS.MaSach
JOIN PHATHANH PH ON PH.MaSach = TS.MaSach
WHERE S.TenSach = N'Cấu trúc rời rạc'
AND PH.NXB = N'Nhà xuất bản ĐHQG-HCM'

-- Cau 6
SELECT TG.MaTG, TG.HoTen, COUNT(PH.MaSach) AS SOSACHDAPHATHANH
FROM TACGIA TG 
LEFT JOIN TACGIA_SACH TS ON TG.MaTG = TS.MaTG
LEFT JOIN PHATHANH PH ON PH.MaSach = TS.MaSach
WHERE YEAR(PH.NgayPH) = 2024
GROUP BY TG.MaTG, TG.HoTen
ORDER BY SOSACHDAPHATHANH DESC

-- Cau 7
SELECT DG.MaDG, DG.TenDG
FROM DOCGIA DG
JOIN MUONSACH MS ON DG.MaDG = MS.MaDG
JOIN SACH S ON S.MaSach = MS.MaSach
WHERE YEAR(MS.NgayMuon) = 2024
GROUP BY DG.MaDG, DG.TenDG
HAVING COUNT(DISTINCT S.TheLoai) >= 3

-- Cau 8
SELECT PH.NXB
FROM PHATHANH PH
JOIN SACH S ON PH.MaSach = S.MaSach
GROUP BY PH.NXB
HAVING COUNT(DISTINCT S.TheLoai) > 5
EXCEPT
SELECT PH.NXB
FROM PHATHANH PH
JOIN MUONSACH MS ON PH.MaSach = MS.MaSach

-- Cau 9
WITH TEMP AS (SELECT DG.MaDG, DG.TenDG
	FROM DOCGIA DG
	JOIN MUONSACH MS ON MS.MaDG = DG.MaDG
	JOIN SACH S ON S.MaSach = MS.MaSach
	WHERE S.TheLoai = N'Khoa học viễn tưởng'
	AND YEAR(MS.NgayMuon) = 2024
	INTERSECT
	SELECT DG.MaDG, DG.TenDG
	FROM DOCGIA DG
	JOIN MUONSACH MS ON MS.MaDG = DG.MaDG
	JOIN SACH S ON S.MaSach = MS.MaSach
	WHERE S.TheLoai = N'Kinh tế'
	AND YEAR(MS.NgayMuon) = 2024
)
SELECT DG.MaDG, DG.TenDG
FROM TEMP DG
GROUP BY DG.MaDG, DG.TenDG
HAVING COUNT(DG.MaDG) = (SELECT COUNT(MaSach)
	FROM SACH 
	WHERE TheLoai = 'Khoa học viễn tưởng'
	OR TheLoai = 'Kinh tế')
