-- 24520602 -- Nguyễn Duy Hưng

-- I.9
GO
CREATE TRIGGER Update_LOP
ON LOP
AFTER UPDATE
AS
BEGIN
	IF UPDATE(TRGLOP)
	BEGIN
		IF EXISTS(
		   SELECT 1
		   FROM INSERTED I
		   JOIN HOCVIEN V ON I.TRGLOP = V.MAHV
		   WHERE I.MALOP <> V.MALOP
		   )
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'Lớp trưởng của một lớp phải là học viên của lớp đó.', 16, 1) 
		END
	END
END

GO
CREATE TRIGGER Delete_HOCVIEN
ON HOCVIEN
AFTER DELETE
AS
BEGIN
	IF EXISTS(
	   SELECT 1
	   FROM DELETED DEL
	   JOIN LOP L ON DEL.MAHV = L.TRGLOP
	)
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR(N'Lớp trưởng của một lớp phải là học viên của lớp đó.', 16, 1) 
	END
END

GO 
CREATE TRIGGER Update_HOCVIEN
ON HOCVIEN
AFTER UPDATE
AS
BEGIN
	IF UPDATE(MALOP)
	BEGIN
		IF EXISTS (
           SELECT 1
           FROM INSERTED I
           JOIN LOP L ON I.MAHV = L.TRGLOP
           WHERE I.MALOP <> L.MALOP
        ) 
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'Lớp trưởng của một lớp phải là học viên của lớp đó.', 16, 1) 
		END
	END
END

-- I.10
GO
CREATE TRIGGER Updata_KHOA
ON KHOA
AFTER UPDATE
AS
BEGIN
	IF UPDATE(TRGKHOA)
	BEGIN
		IF EXISTS(
			SELECT 1
			FROM INSERTED I
			JOIN GIAOVIEN G ON I.TRGKHOA = G.MAGV
			WHERE I.MAKHOA <> G.MAKHOA
			OR G.HOCVI NOT IN ('TS', 'PTS') 
		)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”.', 16, 1)
		END
	END
END

GO
CREATE TRIGGER Update_GIAOVIEN
ON GIAOVIEN
AFTER UPDATE
AS
BEGIN
	IF UPDATE(MAKHOA) OR UPDATE(HOCVI)
	BEGIN
		IF EXISTS(
			SELECT 1
			FROM INSERTED I
			JOIN KHOA K ON I.MAGV = K.TRGKHOA
			WHERE I.MAKHOA <> K.MAKHOA
			OR I.HOCVI NOT IN ('TS', 'PTS')
		)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”.', 16, 1)
		END
	END
END

GO
CREATE TRIGGER Delete_GIAOVIEN
ON GIAOVIEN
AFTER DELETE
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM DELETED DEL
		JOIN KHOA K ON DEL.MAGV = K.TRGKHOA
	)
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR(N'Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”.', 16, 1)
	END 
END

-- I.15
GO
CREATE TRIGGER KIEMTRATHI
ON KETQUATHI 
FOR INSERT, UPDATE 
AS 
BEGIN
	IF EXISTS(
		SELECT 1
		FROM INSERTED I
		JOIN HOCVIEN HV ON I.MAHV = HV.MAHV
		JOIN GIANGDAY GD ON HV.MALOP = GD.MALOP AND I.MAMH = GD.MAMH
		WHERE I.NGTHI < GD.DENNGAY
	) 
	BEGIN 
		ROLLBACK TRANSACTION
		RAISERROR(N'Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này.', 16, 1)
	END
END

-- I.16
GO
CREATE TRIGGER KIEMTRASOLUONGMON
ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN 
	IF EXISTS(
		SELECT 1
		FROM (
			SELECT MALOP, MAMH, HOCKY, NAM FROM GIANGDAY 
            WHERE MALOP IN (SELECT MALOP FROM INSERTED)
            AND HOCKY IN (SELECT HOCKY FROM INSERTED)
            AND NAM IN (SELECT NAM FROM INSERTED)
            UNION
			SELECT MALOP, MAMH, HOCKY, NAM FROM INSERTED
			) AS TONGMONHOC
		GROUP BY TONGMONHOC.HOCKY, TONGMONHOC.NAM, TONGMONHOC.MALOP
		HAVING COUNT(DISTINCT TONGMONHOC.MAMH) > 3)
	BEGIN 
		ROLLBACK TRANSACTION
		RAISERROR(N'Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn.', 16, 1)
	END
END

-- I.17
GO
CREATE TRIGGER INSERT_HOCVIEN
ON HOCVIEN
AFTER INSERT
AS
BEGIN
	UPDATE LOP
	SET SISO = SISO + 1
	WHERE MALOP IN (SELECT MALOP FROM INSERTED)
END

GO
CREATE TRIGGER DELETE_HOCVIEN
ON HOCVIEN
AFTER DELETE
AS
BEGIN
	UPDATE LOP
	SET SISO = SISO 1 1
	WHERE MALOP IN (SELECT MALOP FROM DELETED)
END

GO
CREATE TRIGGER UPDATE_HOCVIEN
ON HOCVIEN
AFTER UPDATE
AS
BEGIN 
	UPDATE LOP
	SET SISO = SISO + 1
	WHERE MALOP IN (SELECT MALOP FROM INSERTED)

	UPDATE LOP
	SET SISO = SISO 1 1
	WHERE MALOP IN (SELECT MALOP FROM DELETED)
END

GO
CREATE TRIGGER UPDATE_LOP
ON LOP
AFTER UPDATE
AS
BEGIN
	IF UPDATE(SISO)
	BEGIN
		RAISERROR(N'Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó.', 16, 1)
		ROLLBACK TRANSACTION
	END
END

-- I.18
GO
CREATE TRIGGER INSERT_UPDATE_DIEUKIEN
ON DIEUKIEN
AFTER INSERT, UPDATE
AS 
BEGIN
	IF EXISTS(
		SELECT 1
		FROM INSERTED I
		WHERE MAMH = MAMH_TRUOC
		)
	BEGIN
		RAISERROR(N'LỖI', 16, 1)
		ROLLBACK TRANSACTION
	END

	IF EXISTS(
		SELECT 1
		FROM INSERTED I
		JOIN DIEUKIEN DK ON I.MAMH = DK.MAMH_TRUOC 
		AND I.MAMH_TRUOC = DK.MAMH
		AND I.MAMH <> DK.MAMH
		)
	BEGIN
		RAISERROR(N'LỖI', 16, 1)
		ROLLBACK TRANSACTION
	END
END

-- I.19
GO
CREATE TRIGGER INSERT_GIAOVIEN
ON GIAOVIEN
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM INSERTED I 
		JOIN GIAOVIEN GV ON I.HOCVI = GV.HOCVI
		AND I.HOCHAM = GV.HOCHAM
		AND I.HESO = GV.HESO
		WHERE I.MUCLUONG <> GV.MUCLUONG
		AND I.MAGV <> GV.MAGV
	)
	BEGIN
		RAISERROR(N'LỖI', 16, 1)
		ROLLBACK TRANSACTION
	END
END

GO
CREATE TRIGGER UPDATE_GIAOVIEN
ON GIAOVIEN
AFTER UPDATE
AS
BEGIN
	IF UPDATE(HOCVI) OR UPDATE(HOCHAM) OR UPDATE(HESO)
	BEGIN
		IF EXISTS(
			SELECT 1
			FROM INSERTED I 
			JOIN GIAOVIEN GV ON I.HOCVI = GV.HOCVI
			AND I.HOCHAM = GV.HOCHAM
			AND I.HESO = GV.HESO
			WHERE I.MUCLUONG <> GV.MUCLUONG
			AND I.MAGV <> GV.MAGV
		)
		BEGIN
			RAISERROR(N'LỖI', 16, 1)
			ROLLBACK TRANSACTION
		END
	END
END

-- I.20
GO
CREATE TRIGGER INSERT_KETQUATHI
ON KETQUATHI
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT 1 
		FROM INSERTED I
		WHERE I.LANTHI > 1
		AND EXISTS(
			SELECT 1
			FROM KETQUATHI 
			WHERE MAMH = I.MAMH
			AND MAHV = I.MAHV
			AND LANTHI < I.LANTHI
			AND DIEM >= 5.0
		)
	)
	BEGIN
		RAISERROR(N'LỖI', 16, 1)
		ROLLBACK TRANSACTION
	END
END

GO
CREATE TRIGGER UPDATE_KETQUATHI
ON KETQUATHI
AFTER UPDATE
AS
BEGIN
	IF UPDATE(LANTHI) OR UPDATE(DIEM)
	BEGIN
		IF EXISTS(
			SELECT 1 
			FROM INSERTED I
			WHERE I.LANTHI > 1
			AND EXISTS(
				SELECT 1
				FROM KETQUATHI 
				WHERE MAMH = I.MAMH
				AND MAHV = I.MAHV
				AND LANTHI < I.LANTHI
				AND DIEM >= 5.0
			)
		)
		BEGIN
			RAISERROR(N'LỖI', 16, 1)
			ROLLBACK TRANSACTION
		END
	END
END

-- I.21
GO 
CREATE TRIGGER INSERTED_KETQUATHI
ON KETQUATHI
AFTER INSERT
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM INSERTED I 
		WHERE LANTHI > 1
		AND EXISTS(
			SELECT 1
			FROM KETQUATHI
			WHERE MAHV = I.MAHV
			AND MAMH = I.MAMH
			AND LANTHI < I.LANTHI
			AND NGTHI >= I.NGTHI
		)
	)
	BEGIN
		RAISERROR(N'LỖI', 16, 1)
		ROLLBACK TRANSACTION
	END
END

GO 
CREATE TRIGGER UPDATE_KETQUATHI
ON KETQUATHI
AFTER UPDATE
AS
BEGIN
	IF UPDATE(NGTHI)
	BEGIN
		IF EXISTS(
			SELECT 1
			FROM INSERTED I 
			WHERE LANTHI > 1
			AND EXISTS(
				SELECT 1
				FROM KETQUATHI
				WHERE MAHV = I.MAHV
				AND MAMH = I.MAMH
				AND LANTHI < I.LANTHI
				AND NGTHI >= I.NGTHI
			)
		)
		BEGIN
			RAISERROR(N'LỖI', 16, 1)
			ROLLBACK TRANSACTION
		END
	END
END

-- I.22
GO
CREATE TRIGGER INSERT_UPDATE_KETQUATHI
ON KETQUATHI
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM INSERTED I
		JOIN HOCVIEN ON I.MAHV = HOCVIEN.MAHV
		JOIN GIANGDAY ON I.MAMH = GIANGDAY.MAMH 
		AND HOCVIEN.MALOP = GIANGDAY.MALOP
		WHERE I.NGTHI < GIANGDAY.DENNGAY
	)
	BEGIN
		RAISERROR(N'LỖI', 16, 1)
		ROLLBACK TRANSACTION
	END
END

-- I.23
GO
CREATE TRIGGER TRG_GIANGDAY
ON GIANGDAY
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS(
        SELECT 1
        FROM INSERTED I
        JOIN DIEUKIEN DK ON I.MAMH = DK.MAMH
        JOIN GIANGDAY TRUOC ON DK.MAMH_TRUOC = TRUOC.MAMH
        AND TRUOC.MALOP = I.MALOP 
        WHERE I.TUNGAY <= TRUOC.DENNGAY
    )
    BEGIN
        RAISERROR(N'Lỗi: Thời gian bắt đầu giảng dạy môn học sau phải lớn hơn thời gian kết thúc của môn học tiên quyết (học trước).', 16, 1)
        ROLLBACK TRANSACTION
        RETURN
    END
END

-- I.24
GO
CREATE TRIGGER TRGGER_GIANGDAY
ON GIANGDAY
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS(
        SELECT 1
        FROM INSERTED I
        JOIN GIAOVIEN GV ON I.MAGV = GV.MAGV
        JOIN MONHOC MH ON I.MAMH = MH.MAMH
        WHERE GV.MAKHOA <> MH.MAKHOA 
    )
    BEGIN
        RAISERROR(N'Lỗi: Giáo viên chỉ được phân công dạy những môn học thuộc khoa mà giáo viên đó phụ trách.', 16, 1)
        ROLLBACK TRANSACTION
        RETURN
    END
END

-- II

-- II.1
UPDATE GIAOVIEN SET HESO = HESO + 0.2 WHERE MAGV IN (SELECT TRGKHOA FROM KHOA)

-- II.2
ALTER TABLE HOCVIEN ADD DIEMTB FLOAT

UPDATE HOCVIEN SET DIEMTB = (
	SELECT SUM(DIEM) / COUNT(MAMH)
	FROM KETQUATHI LAN1
	WHERE HOCVIEN.MAHV = LAN1.MAHV
	AND LAN1.LANTHI = (
		SELECT MAX(LANTHI)
		FROM KETQUATHI LAN2
		WHERE LAN1.MAHV = LAN2.MAHV
		AND LAN1.MAMH = LAN2.MAMH
	)
)

UPDATE HOCVIEN SET DIEMTB = 0.0 WHERE DIEMTB IS NULL

-- II.3
UPDATE HOCVIEN
SET GHICHU = N'Cam thi' 
WHERE MAHV IN (
    SELECT MAHV
    FROM KETQUATHI
    WHERE LANTHI = 3       
    AND DIEM < 5.0  
    GROUP BY MAHV
)

-- II.4
UPDATE HOCVIEN
SET XEPLOAI = 
CASE
    WHEN DIEMTB >= 9 THEN N'XS'
    WHEN DIEMTB >= 8 AND DIEMTB < 9 THEN N'G' 
    WHEN DIEMTB >= 6.5 AND DIEMTB < 8 THEN N'K'
    WHEN DIEMTB >= 5 AND DIEMTB < 6.5 THEN N'TB' 
    ELSE N'Y'
END

-- III.4
SELECT HOCVIEN.MAHV, HO + ' ' + TEN AS HOTEN
FROM HOCVIEN 
JOIN KETQUATHI ON HOCVIEN.MAHV =  KETQUATHI.MAHV
WHERE MALOP = 'K11' 
AND MAMH = 'CTRR'
AND LANTHI = 1
AND DIEM < 5.0

-- III.5
SELECT HOCVIEN.MAHV, HO + ' ' + TEN AS HOTEN
FROM HOCVIEN 
JOIN KETQUATHI ON HOCVIEN.MAHV =  KETQUATHI.MAHV
WHERE MALOP LIKE 'K%%'
AND MAMH = 'CTRR'
GROUP BY HOCVIEN.MAHV, HO, TEN
HAVING MAX(DIEM) < 5.0

-- III.6
SELECT DISTINCT TENMH
FROM MONHOC
JOIN GIANGDAY ON MONHOC.MAMH = GIANGDAY.MAMH
JOIN GIAOVIEN ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE HOTEN = 'Tran Tam Thanh' 
AND HOCKY = 1
AND NAM = 2006

-- III.7
SELECT MONHOC.MAMH, TENMH
FROM MONHOC
JOIN GIANGDAY ON MONHOC.MAMH = GIANGDAY.MAMH
JOIN LOP ON GIANGDAY.MAGV = LOP.MAGVCN
WHERE HOCKY = 1
AND LOP.MALOP = 'K11'
AND NAM = 2006

-- III.8
SELECT DISTINCT HV.HO + ' ' + HV.TEN AS HOTENLOPTRUONG
FROM GIAOVIEN GV
JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV 
JOIN LOP L ON GD.MALOP = L.MALOP      
JOIN HOCVIEN HV ON L.TRGLOP = HV.MAHV
JOIN MONHOC MH ON GD.MAMH = MH.MAMH   
WHERE GV.HOTEN = 'Nguyen To Lan'    
AND MH.TENMH = 'Co So Du Lieu';

-- III.9
SELECT MAMH_TRUOC, MH2.TENMH
FROM MONHOC MH1
JOIN DIEUKIEN ON MH1.MAMH = DIEUKIEN.MAMH
JOIN MONHOC MH2 ON MH2.MAMH = DIEUKIEN.MAMH_TRUOC
WHERE MH1.TENMH = 'Co So Du Lieu'

-- III.10
SELECT MH1.MAMH, MH1.TENMH
FROM MONHOC MH1
JOIN DIEUKIEN ON MH1.MAMH = DIEUKIEN.MAMH
JOIN MONHOC MH2 ON MH2.MAMH = DIEUKIEN.MAMH_TRUOC
WHERE MH2.TENMH = 'Cau Truc Roi Rac'

-- III.11
(SELECT HOTEN
FROM GIAOVIEN
JOIN GIANGDAY ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE MALOP = 'K11'
AND MAMH = 'CTRR'
AND HOCKY = 1
AND NAM = 2006)
INTERSECT
(SELECT HOTEN
FROM GIAOVIEN
JOIN GIANGDAY ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE MALOP = 'K12'
AND MAMH = 'CTRR'
AND HOCKY = 1
AND NAM = 2006)

-- III.12
SELECT HOCVIEN.MAHV, HO + ' ' + TEN AS HOTEN
FROM HOCVIEN
JOIN KETQUATHI ON KETQUATHI.MAHV = HOCVIEN.MAHV
WHERE LANTHI = 1 
AND DIEM < 5.0 
AND MAMH = 'CSDL'
AND NOT EXISTS(SELECT 1 
	FROM KETQUATHI KQ 
	WHERE KQ.MAHV = HOCVIEN.MAHV
	AND KQ.MAMH = 'CSDL'
	AND LANTHI > 1
)
	
-- III.13
(SELECT MAGV, HOTEN
FROM GIAOVIEN)
EXCEPT
(SELECT GIAOVIEN.MAGV, HOTEN
FROM GIAOVIEN
JOIN GIANGDAY ON GIANGDAY.MAGV = GIAOVIEN.MAGV)

-- III.14
(SELECT MAGV, HOTEN
FROM GIAOVIEN)
EXCEPT
(SELECT GIAOVIEN.MAGV, HOTEN
FROM GIAOVIEN
JOIN GIANGDAY ON GIANGDAY.MAGV = GIAOVIEN.MAGV
JOIN MONHOC ON MONHOC.MAMH = GIANGDAY.MAMH
WHERE GIAOVIEN.MAKHOA = MONHOC.MAKHOA)

-- III.15
(SELECT HO + ' ' + TEN AS HOTEN
FROM HOCVIEN
JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE MALOP = 'K11'
GROUP BY HOCVIEN.MAHV, HO, TEN, MAMH
HAVING MAX(LANTHI) > 3 AND MAX(DIEM) < 5.0) 
UNION
(SELECT HO + ' ' + TEN AS HOTEN 
FROM HOCVIEN
JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE MALOP = 'K11'
AND LANTHI = 2
AND MAMH = 'CTRR'
AND DIEM = 5.0)

-- III.16
SELECT HOTEN
FROM GIAOVIEN
JOIN GIANGDAY ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE MAMH = 'CTRR'
GROUP BY HOTEN, GIAOVIEN.MAGV, HOCKY, NAM
HAVING COUNT(MALOP) >= 2

-- III.17
SELECT HV.MAHV, HO + ' ' + TEN AS HOTEN, DIEM
FROM HOCVIEN HV
JOIN KETQUATHI ON HV.MAHV = KETQUATHI.MAHV
WHERE MAMH = 'CSDL'
AND LANTHI = (
	SELECT MAX(KQ.LANTHI)
	FROM KETQUATHI KQ
	WHERE MAMH = 'CSDL'
	AND KQ.MAHV = HV.MAHV
)

-- III.18
SELECT HV.MAHV, HO + ' ' + TEN AS HOTEN, MAX(DIEM) AS DIEMCAONHAT
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
JOIN MONHOC MH ON KQ.MAMH = MH.MAMH
WHERE TENMH = 'Co So Du Lieu'
GROUP BY HV.MAHV, HO, TEN

-- III.19
SELECT MAKHOA, TENKHOA
FROM KHOA
GROUP BY MAKHOA, TENKHOA, NGTLAP
HAVING NGTLAP = (
	SELECT MIN(K.NGTLAP)
	FROM KHOA K 
)

-- III.20
SELECT COUNT(*) AS SOLUONGGIAOVIEN
FROM GIAOVIEN
WHERE HOCHAM IN ('GS', 'PGS')

-- III.21
SELECT MAKHOA, COUNT(MAGV)
FROM GIAOVIEN
WHERE HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS')
GROUP BY MAKHOA

-- III.22
SELECT KQT.MAMH,
COUNT(CASE
	WHEN DIEM >= 5.0 THEN 1
	ELSE NULL
	END) AS SOLUONGDAT,
COUNT(CASE
	WHEN DIEM < 5.0 THEN 1
	ELSE NULL
	END) AS SOLUONGKHONGDAT
FROM KETQUATHI KQT
WHERE LANTHI = (SELECT MAX(KQ.LANTHI) 
	FROM KETQUATHI KQ
	WHERE KQ.MAHV = KQT.MAHV
	AND KQ.MAMH = KQT.MAMH
	)
GROUP BY MAMH

-- III.23
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
JOIN LOP L ON GV.MAGV = L.MAGVCN
WHERE EXISTS(SELECT 1 
	FROM GIANGDAY GD
	WHERE GV.MAGV = GD.MAGV
	AND GD.MALOP = L.MALOP
)

-- III.24
SELECT HO + ' ' + TEN AS HOTEN
FROM HOCVIEN HV
JOIN LOP L ON HV.MAHV = L.TRGLOP
WHERE L.MALOP IN (
	SELECT MALOP
	FROM HOCVIEN
	GROUP BY MALOP
	HAVING COUNT(*) = (SELECT MAX(SOLUONG)
		FROM (SELECT COUNT(*) AS SOLUONG
		FROM HOCVIEN
		GROUP BY MALOP
		) AS SUB
	)
)

-- III.25
SELECT HV.HO + ' ' + HV.TEN AS HoTenLopTruong
FROM HOCVIEN HV
JOIN LOP L ON HV.MAHV = L.TRGLOP 
JOIN KETQUATHI KQ ON KQ.MAHV = HV.MAHV
JOIN (SELECT MAHV, MAMH, MAX(DIEM) AS DIEMCAONHAT
	FROM KETQUATHI
    GROUP BY MAHV, MAMH
    ) AS DiemMax ON KQ.MAHV = DiemMax.MAHV AND KQ.MAMH = DiemMax.MAMH
WHERE KQ.DIEM = DiemMax.DIEMCAONHAT 
AND KQ.DIEM < 5.0 
GROUP BY HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(DISTINCT KQ.MAMH) >= 4;

-- III.26
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV 
GROUP BY HV.MAHV, HV.HO, HV.TEN
HAVING HV.MAHV IN (
SELECT KQT.MAHV
FROM KETQUATHI KQT
GROUP BY KQT.MAHV
HAVING COUNT(CASE
	WHEN KQ.DIEM BETWEEN 9 AND 10 THEN 1
	ELSE NULL
	END) = (SELECT MAX(T.SOLUONGDIEM) 
		FROM (SELECT COUNT(CASE	
			WHEN KETQUA.DIEM BETWEEN 9 AND 10 THEN 1
			ELSE NULL
			END) AS SOLUONGDIEM
			FROM KETQUATHI KETQUA
			GROUP BY KETQUA.MAHV
		) AS T
	) 
)

-- III.27
GO
WITH SOLANDAT AS (
	SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN, HV.MALOP,
	COUNT(CASE WHEN KQ.DIEM BETWEEN 9.0 AND 10.0 THEN 1 ELSE NULL END) AS SOLUONG,
	RANK() OVER (
		PARTITION BY HV.MALOP
		ORDER BY COUNT(CASE WHEN KQ.DIEM BETWEEN 9.0 AND 10.0 THEN 1 ELSE NULL END) DESC
	) AS HANG
	FROM HOCVIEN HV
	JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
	GROUP BY HV.MAHV, HV.HO, HV.TEN, HV.MALOP
)
SELECT MAHV, HOTEN, MALOP
FROM SOLANDAT
WHERE HANG = 1

-- III.28
SELECT GD.HOCKY, GD.NAM, GV.MAGV, GV.HOTEN,
COUNT(DISTINCT GD.MAMH) AS SOMONHOC,
COUNT(DISTINCT GD.MALOP) AS SOLOPHOC
FROM GIANGDAY GD
JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
GROUP BY GD.HOCKY, GD.NAM, GV.MAGV, GV.HOTEN

-- III.29
GO
WITH SOLUONG AS (
	SELECT GD.HOCKY, GD.NAM, GV.MAGV, GV.HOTEN,
	COUNT(DISTINCT GD.MALOP) AS SOLOPHOC,
	RANK() OVER (
		PARTITION BY GD.HOCKY, GD.NAM
		ORDER BY COUNT(DISTINCT GD.MALOP) DESC
	) AS HANG
	FROM GIANGDAY GD
	JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
	GROUP BY GD.HOCKY, GD.NAM, GV.MAGV, GV.HOTEN
)
SELECT HOCKY, NAM, MAGV, HOTEN
FROM SOLUONG
WHERE HANG = 1

-- III.30
GO 
WITH LOPHOC AS (	
	SELECT MH.MAMH, MH.TENMH,
	COUNT(CASE
		WHEN KQ.LANTHI = 1 AND KQ.DIEM < 5.0 THEN 1
		ELSE NULL
		END) AS SOLUONG,
	RANK() OVER(
		PARTITION BY MH.MAMH, MH.TENMH
		ORDER BY COUNT(CASE WHEN KQ.LANTHI = 1 AND KQ.DIEM < 5.0 THEN 1 ELSE NULL END) DESC
	) AS HANG
	FROM MONHOC MH
	JOIN KETQUATHI KQ ON MH.MAMH = KQ.MAMH
	GROUP BY MH.MAMH, MH.TENMH
)
SELECT MAMH, TENMH
FROM LOPHOC
WHERE HANG = 1

-- III.31
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
WHERE KQ.LANTHI = 1
GROUP BY HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(KQ.MAMH) = COUNT(CASE WHEN KQ.DIEM >= 5.0 THEN KQ.MAMH ELSE NULL END)

-- III.32
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HoTen
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
JOIN (SELECT MAHV, MAMH, MAX(DIEM) AS DIEM_MAX
        FROM KETQUATHI
        GROUP BY MAHV, MAMH
    ) AS MaxDiemMon ON HV.MAHV = MaxDiemMon.MAHV AND KQ.MAMH = MaxDiemMon.MAMH
WHERE KQ.DIEM = MaxDiemMon.DIEM_MAX
GROUP BY HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(DISTINCT KQ.MAMH) = COUNT(CASE 
    WHEN KQ.DIEM >= 5.0 THEN KQ.MAMH
    ELSE NULL
END);

-- III.33
SELECT
    HV.MAHV,
    HV.HO + ' ' + HV.TEN AS HoTen
FROM
    HOCVIEN HV
JOIN
    KETQUATHI KQ ON HV.MAHV = KQ.MAHV
WHERE
    KQ.LANTHI = 1 
    AND KQ.DIEM >= 5.0
GROUP BY
    HV.MAHV, HV.HO, HV.TEN
HAVING
    COUNT(DISTINCT KQ.MAMH) = (SELECT COUNT(MAMH) FROM MONHOC); 

-- III.34
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HoTen
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
JOIN (SELECT MAHV, MAMH, MAX(DIEM) AS DIEM_MAX
        FROM KETQUATHI
        GROUP BY MAHV, MAMH
    ) AS MaxDiemMon ON HV.MAHV = MaxDiemMon.MAHV AND KQ.MAMH = MaxDiemMon.MAMH
WHERE KQ.DIEM = MaxDiemMon.DIEM_MAX AND KQ.DIEM >= 5.0 
GROUP BY HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(DISTINCT KQ.MAMH) = (SELECT COUNT(MAMH) FROM MONHOC); 

-- III.35
WITH DiemCaoNhatMon AS (
    SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HoTen, MH.TENMH, KQ.DIEM,
        ROW_NUMBER() OVER(PARTITION BY HV.MAHV, MH.MAMH ORDER BY KQ.LANTHI DESC) AS LanCuoi,
        RANK() OVER (
            PARTITION BY MH.MAMH
            ORDER BY KQ.DIEM DESC
        ) AS HangMon
    FROM HOCVIEN HV
    JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
    JOIN MONHOC MH ON KQ.MAMH = MH.MAMH
)
SELECT MAHV, HoTen, TENMH, DIEM
FROM DiemCaoNhatMon
WHERE LanCuoi = 1 AND HangMon = 1;