-- 24520602 -- Nguyen Duy Hung

CREATE DATABASE QlyHangHoa

USE QlyHangHoa

CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(5) PRIMARY KEY,
	TENNCC VARCHAR(20),
	TRANGTHAI NUMERIC(2,0),
	THANHPHO VARCHAR(30)
)

CREATE TABLE PHUTUNG
(
	MAPT VARCHAR(5) PRIMARY KEY,
	TENPT VARCHAR(10),
	MAUSAC VARCHAR(10),
	KHOILUONG FLOAT,
	THANHPHO VARCHAR(10)
)

CREATE TABLE VANCHUYEN
(
	MANCC VARCHAR(5),
	MAPT VARCHAR(5),
	SOLUONG NUMERIC(5,0),
	PRIMARY KEY(MANCC,MAPT),
	FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
	FOREIGN KEY (MAPT) REFERENCES PHUTUNG(MAPT)
)

INSERT INTO NHACUNGCAP (MANCC, TENNCC, TRANGTHAI, THANHPHO) VALUES 
('NCC01', 'Viet AutoPro', 1, 'Ha Noi'),
('NCC02', 'Dong Nam Spares', 0, 'Hai Phong'),
('NCC03', 'Thanh Binh Tech', 1, 'Da Nang'),
('NCC04', 'MegaParts Co', 0, 'HCM'),
('NCC05', 'Green Motor', 0, 'Can Tho')

INSERT INTO PHUTUNG (MAPT, TENPT, MAUSAC, KHOILUONG, THANHPHO) VALUES
('PT01', 'LoXo', 'Xanh', 0.8, 'Ha Noi'),
('PT02', 'BuLongInox', 'Trang', 0.3, 'Hai Phong'),
('PT03', 'DaiTruyen', 'Den', 1.2, 'Da Nang'),
('PT04', 'PhanhDia', 'Do', 2.5, 'HCM'),
('PT05', 'LopXe', 'Den', 3.8, 'Can Tho')

INSERT INTO VANCHUYEN (MANCC, MAPT, SOLUONG) VALUES
('NCC01', 'PT02', 120),
('NCC01', 'PT03', 180),
('NCC02', 'PT04', 140),
('NCC03', 'PT05', 320),
('NCC04', 'PT01', 260)