CREATE DATABASE QlyChanNuoi

USE QlyChanNuoi

CREATE TABLE CSCHANNUOI (
	MACS CHAR(5) PRIMARY KEY,
	TENCS VARCHAR(255),
	LOAICS VARCHAR(255),
	NGDAIDIEN VARCHAR(255),
	NGTL SMALLDATETIME,
	DTHOAI CHAR(10)
)

CREATE TABLE GIONGVN (
	MAGIONG CHAR(5) PRIMARY KEY,
	TENGIONG VARCHAR(255),
	LOAIVN VARCHAR(255)
)

CREATE TABLE DIEUKIENCN (
	MADK CHAR(5) PRIMARY KEY,
	MACS CHAR(5) FOREIGN KEY REFERENCES CSCHANNUOI(MACS),
	QUYMO INT,
	KCXLCT INT,
	KCKDC INT,
)

CREATE TABLE GPCN (
	MAGP CHAR(5) PRIMARY KEY,
	MACS CHAR(5) FOREIGN KEY REFERENCES CSCHANNUOI(MACS),
	NGCAP SMALLDATETIME,
	SOGP VARCHAR(255),
	SOGIONG INT
)

CREATE TABLE CTGP (
	MAGP CHAR(5) FOREIGN KEY REFERENCES GPCN(MAGP),
	MAGIONG CHAR(5) FOREIGN KEY REFERENCES GIONGVN(MAGIONG),
	SL INT,
	PRIMARY KEY (MAGP, MAGIONG)
)

CREATE TABLE DOTCN (
	MADOTCN CHAR(5) PRIMARY KEY,
	MACS CHAR(5) FOREIGN KEY REFERENCES CSCHANNUOI(MACS),
	MAGIONG CHAR(5) FOREIGN KEY REFERENCES GIONGVN(MAGIONG),
	SLVN INT,
	NGBD SMALLDATETIME,
	PHGTHUC VARCHAR(255),
	NGXUATDK SMALLDATETIME
)

INSERT INTO CSCHANNUOI VALUES 
('CS001', 'Hoang mai', 'Nong ho', 'Nguyen Thanh Son', '2019-10-19', '0971507394'),
('CS002', 'Cong ty TNHH Phung', 'Trang trai quy mo vua', 'Pham The Hung', '2009-10-20', '0364266792'),
('CS003', 'Green Farm', 'Trang trai quy mo nho', 'Ho Trung Dai', '2018-09-15', '0356266782')

INSERT INTO GIONGVN VALUES
('G001', 'Bo vang Viet Nam', 'Bo'),
('G002', 'Bo Bay Nui', 'Bo'),
('G003', 'De nui Ninh Binh', 'De')

INSERT INTO DIEUKIENCN VALUES
('DK001', 'CS001', 10, 250, 300),
('DK002', 'CS001', 10, 200, 350),
('DK003', 'CS003', 30, 350, 400)

INSERT INTO GPCN VALUES
('GP001', 'CS001', '10/10/2020', '42/001/2020/DKCN', 1),
('GP002', 'CS001', '08/09/2020', '43/001/2020/DKCN', 2),
('GP003', 'CS002', '04/06/2010', '2/002/2010/DKCN', 4)

GO

ALTER TABLE DOTCN ADD CONSTRAINT Check_Phuong_Thuc CHECK (NOT(SLVN >= 100 AND PHGTHUC = 'Tha tu do')) 

GO

CREATE TRIGGER UPDATE_GIONGVN
ON GIONGVN
AFTER UPDATE
AS
BEGIN
	IF UPDATE(LOAIVN)
	BEGIN
		IF EXISTS (SELECT * 
			FROM INSERTED I 
			JOIN DOTCN D ON D.MAGIONG = I.MAGIONG
			WHERE I.LOAIVN = 'Bo'
			AND DATEDIFF(MONTH, NGBD, NGXUATDK) < 12)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('Loi')
		END
	END
END

GO

CREATE TRIGGER INSERT_UPDATE_DOTCN
ON DOTCN
AFTER INSERT, UPDATE
AS
BEGIN
	IF UPDATE(MAGIONG) OR UPDATE(NGBD) OR UPDATE(NGXUATDK)
	BEGIN
		IF EXISTS (SELECT * 
			FROM INSERTED I 
			JOIN GIONGVN G ON G.MAGIONG = I.MAGIONG
			WHERE G.LOAIVN = 'Bo'
			AND DATEDIFF(MONTH, NGBD, NGXUATDK) < 12)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('Loi')
		END
	END
END

GO

SELECT G.MAGIONG, G.TENGIONG
FROM GIONGVN G
JOIN DOTCN D ON D.MAGIONG = G.MAGIONG
WHERE G.LOAIVN = 'Bo'
AND D.PHGTHUC = 'Tha tu do'
AND MONTH(D.NGXUATDK) = 12
AND YEAR(D.NGXUATDK) = 2024

GO

SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C
JOIN DOTCN D ON C.MACS = D.MACS
JOIN GIONGVN G ON G.MAGIONG = D.MAGIONG
WHERE G.LOAIVN = 'De'
AND YEAR(D.NGBD) = 2024
EXCEPT
SELECT C.MACS, C.TENCS
FROM CSCHANNUOI C
JOIN GPCN GP ON GP.MACS = C.MACS
JOIN CTGP CT ON CT.MAGP = GP.MAGP
JOIN GIONGVN G ON G.MAGIONG = CT.MAGIONG
WHERE G.LOAIVN = 'De'

GO

SELECT G.LOAIVN, D.PHGTHUC, AVG(DATEDIFF(MONTH, NGBD, NGXUATDK))
FROM GIONGVN G
JOIN DOTCN D ON G.MAGIONG = D.MAGIONG
GROUP BY G.LOAIVN, D.PHGTHUC

GO

WITH TONGSOLUONG AS (
	SELECT G.LOAIVN, G.MAGIONG, SUM(C.SL) AS TONG 
	FROM GIONGVN G
	JOIN CTGP C ON G.MAGIONG = C.MAGIONG
	JOIN GPCN GP ON GP.MAGP = C.MAGP
	WHERE YEAR(GP.NGCAP) = 2024
	GROUP BY G.MAGIONG, G.LOAIVN
)
SELECT T1.LOAIVN, T1.MAGIONG, T1.TONG
FROM TONGSOLUONG T1
WHERE T1.TONG = (
    SELECT MAX(T2.TONG)
    FROM TONGSOLUONG T2
    WHERE T2.LOAIVN = T1.LOAIVN
)

GO

SELECT C.MACS, C.TENCS 
FROM CSCHANNUOI C
JOIN GPCN GP ON C.MACS = GP.MAGP
JOIN CTGP CT ON CT.MAGP = GP.MAGP
JOIN GIONGVN G ON G.MAGIONG = CT.MAGIONG
WHERE G.LOAIVN = 'Bo'
AND CT.SL >= 20
GROUP BY C.MACS, C.TENCS
HAVING COUNT(DISTINCT CT.MAGIONG) = (SELECT COUNT(*)
	FROM GIONGVN 
	JOIN CTGP ON GIONGVN.MAGIONG = CTGP.MAGIONG
	WHERE LOAIVN = 'Bo' AND SL >= 20)