-- Câu 1

CREATE DATABASE QlyPhim

USE QlyPhim

CREATE TABLE KHACHHANG (
	MAKH CHAR(4) PRIMARY KEY,
	TENKH NVARCHAR(255),
	DIACHI NVARCHAR(255),
	LOAIKH NVARCHAR(255)
)

CREATE TABLE PHIM (
	MAP CHAR(4) PRIMARY KEY,
	TENP NVARCHAR(255),
	GIOIHANDOTUOI INT,
	NGAYCHIEU SMALLDATETIME
)

CREATE TABLE HOADON (
	SOHD CHAR(5) PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	KHUYENMAI FLOAT
)

CREATE TABLE CTHD (
	SOHD CHAR(5) FOREIGN KEY REFERENCES HOADON(SOHD),
	MAP CHAR(4) FOREIGN KEY REFERENCES PHIM(MAP),
	SOLUONG INT,
	PRIMARY KEY (SOHD, MAP)
)

-- Câu 2

INSERT INTO KHACHHANG VALUES
('KH01', 'Tran Thanh Long', '2000-12-22', 'Vang lai'),
('KH02', 'Nguyen Thanh Phong', '1999-7-3', 'Thuong xuyen'),
('KH03', 'Nguyen Viet Truong', '2001-10-16', 'Vang lai')

INSERT INTO PHIM VALUES
('DA01', N'AVATAR: DÒNG CHẢY CỦA NƯỚC', 13, '2022-12-1'),
('DA02', N'ÂM LƯỢNG HỦY DIỆT', 16, '2022-12-18'),
('DA03', N'CUỘC DIỄU HÀNH THẦM LẶNG', 13, '2022-12-20')

INSERT INTO HOADON VALUES
('00001', '2022-11-22', 'KH01', 5),
('00002', '2022-12-4', 'KH03', 5),
('00003', '2022-12-10', 'KH02', 10)

INSERT INTO CTHD VALUES
('00001', 'DA01', 5),
('00001', 'DA02', 2),
('00003', 'DA03', 1)

-- Câu 3

ALTER TABLE PHIM ADD CONSTRAINT Check_Ngay_Chieu CHECK (NOT (GIOIHANDOTUOI = 16 AND NGAYCHIEU < '2022-12-15'))

-- Câu 4

SELECT *
FROM HOADON HD 
WHERE MONTH(HD.NGHD) BETWEEN 10 AND 12
AND YEAR(HD.NGHD) = 2024
ORDER BY HD.KHUYENMAI ASC

-- Câu 5

WITH THONGKE AS (SELECT P.MAP, SUM(CT.SOLUONG) AS SOLUONGVE
	FROM PHIM P
	JOIN CTHD CT ON P.MAP = CT.MAP
	JOIN HOADON HD ON HD.SOHD = CT.SOHD
	WHERE MONTH(HD.NGHD) = 12
	GROUP BY P.MAP
), MINSOLUONG AS (SELECT MIN(SOLUONGVE) AS SOLUONGMIN
	FROM THONGKE
)
SELECT THONGKE.MAP 
FROM THONGKE
JOIN MINSOLUONG ON MINSOLUONG.SOLUONGMIN = THONGKE.SOLUONGVE

-- Câu 6

WITH THONGKE AS (SELECT P.MAP, SUM(CT.SOLUONG) AS SOLUONGVE
	FROM PHIM P
	JOIN CTHD CT ON P.MAP = CT.MAP
	JOIN HOADON HD ON HD.SOHD = CT.SOHD
	WHERE MONTH(HD.NGHD) = 12
	GROUP BY P.MAP
), MAXSOLUONG AS (SELECT MAX(SOLUONGVE) AS SOLUONGMAX
	FROM THONGKE
)
SELECT THONGKE.MAP 
FROM THONGKE
JOIN MAXSOLUONG ON MAXSOLUONG.SOLUONGMAX = THONGKE.SOLUONGVE

-- Câu 7

SELECT P.MAP, P.TENP
FROM PHIM P
JOIN CTHD CT ON CT.MAP = P.MAP
JOIN HOADON HD ON HD.SOHD = CT.SOHD
JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
WHERE KH.LOAIKH = 'Vang lai'
INTERSECT
SELECT P.MAP, P.TENP
FROM PHIM P
JOIN CTHD CT ON CT.MAP = P.MAP
JOIN HOADON HD ON HD.SOHD = CT.SOHD
JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
WHERE KH.LOAIKH = 'Thuong xuyen'

-- Câu 8

SELECT KH.MAKH, KH.TENKH
FROM HOADON HD
JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
JOIN CTHD CT ON CT.SOHD = HD.SOHD
GROUP BY KH.MAKH, KH.TENKH
HAVING COUNT(DISTINCT CT.MAP) = (SELECT COUNT(*) 
	FROM PHIM)