-- 24520602 -- Nguyễn Duy Hưng

USE QlyGiaoVu

-- I.3
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_GT_HV CHECK (GIOITINH IN ('Nam', 'Nu'))
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_GT_GV CHECK (GIOITINH IN ('Nam', 'Nu'))

-- I.4
ALTER TABLE KETQUATHI ALTER COLUMN DIEM DECIMAL(4,2)
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_KQ CHECK (DIEM >= 0 AND DIEM <= 10)

-- I.5
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_KQUA CHECK ((DIEM >= 5 AND KQUA = 'Dat') OR (DIEM < 5 AND KQUA = 'Khong dat'))

-- I.6
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_LANTHI CHECK (LANTHI <= 3)

-- I.7
ALTER TABLE GIANGDAY ADD CONSTRAINT CHECK_HK CHECK (HOCKY IN (1, 2, 3))

-- I.8
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))

-- I.11
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_TUOI CHECK (DATEDIFF(YEAR, NGSINH, GETDATE()) >= 18)

-- I.12
ALTER TABLE GIANGDAY ADD CONSTRAINT CHECK_NGAY CHECK (TUNGAY < DENNGAY)

-- I.13
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_TUOIGV CHECK (DATEDIFF(YEAR, NGSINH, GETDATE()) >= 22)

-- I.14
ALTER TABLE MONHOC ADD CONSTRAINT CHECK_CL CHECK (ABS(TCLT - TCTH) <= 3)

-- III.1
SELECT H.MAHV, H.HO, H.TEN, H.NGSINH, H.MALOP FROM HOCVIEN H JOIN LOP L ON H.MAHV = L.TRGLOP

-- III.2
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN, KQ.LANTHI, KQ.DIEM
FROM HOCVIEN HV
JOIN LOP L ON HV.MALOP = L.MALOP
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
JOIN MONHOC M ON KQ.MAMH = M.MAMH
WHERE L.TENLOP = 'K12' AND M.TENMH = 'CTRR'
ORDER BY HV.TEN ASC, HV.HO ASC;

-- III.3
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN, M.TENMH
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
JOIN MONHOC M ON KQ.MAMH = M.MAMH
WHERE KQ.LANTHI = 1 AND KQ.KQUA = 'Dat';