-- 24520602 -- Nguyễn Duy Hưng

USE QlyBanHang

-- I.2
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)

-- I.3
ALTER TABLE KHACHHANG ADD LOAIKH tinyint

-- I.4
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)

-- I.5
ALTER TABLE SANPHAM DROP COLUMN GHICHU

-- I.6
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(100)

-- I.7
ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_DV CHECK(DVT IN('cay','hop','cai','quyen','chuc'))

-- I.8
ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_GIA CHECK(GIA >= 500)

-- I.9
ALTER TABLE CTHD ADD CONSTRAINT CHECK_SL CHECK(SL > 0)

-- I.10
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_NGAY CHECK(NGDK > NGSINH)

-- II.2
SELECT * INTO SANPHAM1 FROM SANPHAM
SELECT * INTO KHACHHANG1 FROM KHACHHANG

-- II.3
UPDATE SANPHAM1 SET GIA = 1.05 * GIA WHERE NUOCSX = 'Thai Lan'

-- II.4 
UPDATE SANPHAM1 SET GIA = 0.95 * GIA WHERE NUOCSX = 'Trung Quoc' AND GIA <= 10000

-- III.1
SELECT MASP, TENSP FROM SANPHAM WHERE NUOCSX = 'Trung Quoc' 

-- III.2
SELECT MASP, TENSP FROM SANPHAM WHERE DVT = 'cay' OR DVT = 'quyen'

-- III.3
SELECT MASP, TENSP FROM SANPHAM WHERE MASP LIKE 'B%01'

-- III.4
SELECT MASP, TENSP FROM SANPHAM WHERE NUOCSX = 'Trung Quoc' AND (GIA >= 30000 AND GIA <= 40000)

-- III.5
SELECT MASP, TENSP FROM SANPHAM WHERE (NUOCSX = 'Trung Quoc' OR NUOCSX = 'Thai Lan') AND (GIA >= 30000 AND GIA <= 40000)

-- III.6
SELECT SOHD, TRIGIA FROM HOADON WHERE NGHD = '1/1/2007' OR NGHD = '2/1/2007'

-- III.7
SELECT SOHD, TRIGIA FROM HOADON WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007 ORDER BY DAY(NGHD) ASC, TRIGIA DESC