-- Câu 1

CREATE DATABASE QlyNhanVien

USE QlyNhanVien

CREATE TABLE NHANVIEN (
	MANV VARCHAR(3) PRIMARY KEY,
	HOTEN VARCHAR(40),
	NGSINH SMALLDATETIME,
	PHAI VARCHAR(3),
	DIACHI VARCHAR(50),
	MAPHG VARCHAR(2),
	LUONG MONEY
)

CREATE TABLE PHONGBAN (
	MAPHG VARCHAR(2) PRIMARY KEY,
	TENPHG VARCHAR(50),
	TRPHG VARCHAR(3),
	NGNC SMALLDATETIME
)

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_PHONGBAN FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHONGBAN ADD CONSTRAINT FK_NHANVIEN FOREIGN KEY (TRPHG) REFERENCES NHANVIEN(MANV)

CREATE TABLE DEAN (
	MADA VARCHAR(5) PRIMARY KEY,
	TENDA VARCHAR(50),
	DDIEM_DA VARCHAR(50),
	MAPHG VARCHAR(2) FOREIGN KEY REFERENCES PHONGBAN(MAPHG),
	NGBD_DK SMALLDATETIME,
	NGKT_DK SMALLDATETIME
)

CREATE TABLE PHANCONG (
	MANV VARCHAR(3),
	MADA VARCHAR(5),
	THOIGIAN INT,
	PRIMARY KEY (MANV, MADA),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY (MADA) REFERENCES DEAN(MADA)
)

-- Câu 2
	
	-- a

ALTER TABLE NHANVIEN ADD CONSTRAINT CHECK_LUONG CHECK (NOT (MAPHG = 'NC' AND LUONG <= 20000000))

	-- b

GO
CREATE TRIGGER INSERT_UPDATE_PHANCONG
ON PHANCONG
AFTER INSERT, UPDATE
AS
BEGIN
	IF UPDATE(MADA) OR UPDATE(MANV)
	BEGIN
		IF EXISTS (SELECT 1
			FROM INSERTED I
			JOIN NHANVIEN NV ON NV.MANV = I.MANV
			JOIN DEAN DA ON DA.MADA = I.MADA
			WHERE DA.NGBD_DK <= NV.NGSINH)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('LOI')
		END
	END
END

GO
CREATE TRIGGER UPDATE_DEAN
ON DEAN
AFTER UPDATE
AS
BEGIN
	IF UPDATE(NGBD_DK)
	BEGIN
		IF EXISTS (SELECT 1
			FROM INSERTED I
			JOIN PHANCONG PC ON PC.MADA = I.MADA
			JOIN NHANVIEN NV ON NV.MANV = PC.MANV
			WHERE I.NGBD_DK <= NV.NGSINH)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('LOI')
		END
	END
END

GO
CREATE TRIGGER UPDATE_NHANVIEN
ON NHANVIEN
AFTER UPDATE
AS
BEGIN
	IF UPDATE(NGSINH)
	BEGIN
		IF EXISTS (SELECT 1
			FROM INSERTED I
			JOIN PHANCONG PC ON PC.MANV = I.MANV
			JOIN DEAN DA ON DA.MADA = PC.MADA
			WHERE DA.NGBD_DK <= I.NGSINH)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('LOI')
		END
	END
END

-- Câu 3
	
	-- a

SELECT P.TENPHG
FROM PHONGBAN P
JOIN NHANVIEN NV ON NV.MAPHG = P.MAPHG
GROUP BY P.MAPHG, P.TENPHG
HAVING AVG(NV.LUONG) >= 24000000
ORDER BY P.TENPHG DESC

	-- b

SELECT NV.HOTEN
FROM NHANVIEN NV
JOIN PHANCONG PC ON PC.MANV = NV.MANV
JOIN DEAN DA ON DA.MADA = PC.MADA
JOIN PHONGBAN P ON P.MAPHG = DA.MAPHG
WHERE P.TENPHG = 'Nghien Cuu'
AND DA.DDIEM_DA = 'HANOI'

	-- c

SELECT NV.HOTEN, COUNT(DISTINCT PC.MADA) AS SOLUONGDEAN
FROM NHANVIEN NV
JOIN PHANCONG PC ON PC.MANV = NV.MANV
GROUP BY NV.HOTEN

	-- d

SELECT NV.HOTEN
FROM NHANVIEN NV
JOIN PHANCONG PC ON PC.MANV = NV.MANV
JOIN DEAN DA ON DA.MADA = PC.MADA
JOIN PHONGBAN P ON P.MAPHG = DA.MAPHG
WHERE P.TENPHG = 'Nghien Cuu'
EXCEPT
SELECT NV.HOTEN
FROM NHANVIEN NV
JOIN PHANCONG PC ON PC.MANV = NV.MANV
JOIN DEAN DA ON DA.MADA = PC.MADA
JOIN PHONGBAN P ON P.MAPHG = DA.MAPHG
WHERE P.TENPHG <> 'Nghien Cuu'
	
	-- e

SELECT NV.HOTEN
FROM NHANVIEN NV
JOIN PHANCONG PC ON PC.MANV = NV.MANV
JOIN DEAN DA ON DA.MADA = PC.MADA
JOIN PHONGBAN P ON P.MAPHG = DA.MAPHG
WHERE P.TENPHG = 'Dieu Hanh'
GROUP BY NV.MANV, NV.HOTEN
HAVING COUNT(DISTINCT DA.MADA) = (SELECT COUNT(*) 
	FROM DEAN 
	JOIN PHONGBAN ON DEAN.MAPHG = PHONGBAN.MAPHG
	WHERE TENPHG = 'Dieu Hanh')
	
	-- f

WITH SLNVTHEOPHONG AS (SELECT P.MAPHG, P.TENPHG, COUNT(NV.MANV) AS SLNV
	FROM PHONGBAN P
	JOIN NHANVIEN NV ON NV.MAPHG = P.MAPHG
	GROUP BY P.MAPHG, P.TENPHG
), SLNVDONGNHAT AS (SELECT MAX(TP.SLNV) AS MAXSL
	FROM SLNVTHEOPHONG TP
)
SELECT P.TENPHG, NV.HOTEN
FROM PHONGBAN P
JOIN SLNVTHEOPHONG TP ON TP.MAPHG = P.MAPHG 
JOIN SLNVDONGNHAT DN ON DN.MAXSL = TP.SLNV
JOIN NHANVIEN NV ON NV.MANV = P.TRPHG