-- 24520602 -- Nguyễn Duy Hưng

-- I.11
GO
CREATE TRIGGER UPDATE_KHACHHANG
ON KHACHHANG
AFTER UPDATE
AS
BEGIN
	IF UPDATE(NGDK)
	BEGIN
		IF EXISTS (SELECT I.MAKH
			FROM INSERTED I 
			JOIN HOADON HD ON I.MAKH = HD.MAKH
			WHERE I.NGDK > HD.NGHD)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR (N'Ngày mua hàng (NGHD) của một khách hàng thành viên sẽ lớn hơn hoặc bằng ngày khách hàng đó đăng ký thành viên (NGDK). ', 16, 1)
		END
	END
END

GO
CREATE TRIGGER INSERT__HOADON
ON HOADON
AFTER INSERT
AS
BEGIN
	IF EXISTS (SELECT I.SOHD
		FROM INSERTED I 
		JOIN KHACHHANG KH ON I.MAKH = KH.MAKH
		WHERE I.NGHD < KH.NGDK)
	BEGIN 
		ROLLBACK TRANSACTION
		RAISERROR (N'Ngày mua hàng (NGHD) của một khách hàng thành viên sẽ lớn hơn hoặc bằng ngày khách hàng đó đăng ký thành viên (NGDK). ', 16, 1)
	END
END

GO
CREATE TRIGGER UPDATE_HOADON
ON HOADON
AFTER UPDATE
AS
BEGIN
	IF UPDATE(NGHD) OR UPDATE(MAKH)
	BEGIN
		IF EXISTS (SELECT I.SOHD
			FROM INSERTED I 
			JOIN KHACHHANG KH ON I.MAKH = KH.MAKH
			WHERE I.NGHD < KH.NGDK)
		BEGIN 
			ROLLBACK TRANSACTION
			RAISERROR (N'Ngày mua hàng (NGHD) của một khách hàng thành viên sẽ lớn hơn hoặc bằng ngày khách hàng đó đăng ký thành viên (NGDK). ', 16, 1)
		END
	END
END

-- I.12
GO
CREATE TRIGGER UPDATE_NHANVIEN
ON NHANVIEN
AFTER UPDATE
AS
BEGIN
	IF UPDATE(NGVL)
	BEGIN
		IF EXISTS (SELECT I.MANV
			FROM INSERTED I
			JOIN HOADON HD ON I.MANV = HD.MANV
			WHERE HD.NGHD < I.NGVL)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR (N'Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.', 16, 1)
		END
	END
END

GO
CREATE TRIGGER UPDATE_HOADON
ON HOADON
AFTER UPDATE
AS
BEGIN
	IF UPDATE(MANV) OR UPDATE(NGHD)
	BEGIN
		IF EXISTS (SELECT I.SOHD
			FROM INSERTED I 
			JOIN NHANVIEN NV ON NV.MANV = I.MANV
			WHERE NV.NGVL > I.NGHD)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR (N'Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.', 16, 1)
		END
	END
END

GO
CREATE TRIGGER INSERT_HOADON
ON HOADON
AFTER INSERT
AS
BEGIN
	IF EXISTS (SELECT I.SOHD
		FROM INSERTED I 
		JOIN NHANVIEN NV ON NV.MANV = I.MANV
		WHERE NV.NGVL > I.NGHD)
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR (N'Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.', 16, 1)
	END
END

-- I.13
GO
CREATE TRIGGER INSERT_HOADON
ON HOADON
AFTER INSERT
AS
BEGIN
	IF EXISTS (SELECT 1
		FROM INSERTED I
		JOIN CTHD CT ON CT.SOHD = I.SOHD
		GROUP BY CT.SOHD
		HAVING COUNT(CT.SOHD) < 1)
	BEGIN
		RAISERROR('Mỗi một hóa đơn phải có ít nhất một chi tiết hóa đơn.', 16, 1)
		ROLLBACK TRANSACTION
	END
END

GO
CREATE TRIGGER DELETE_SOCTHD
ON CTHD
AFTER DELETE
AS
BEGIN
	IF EXISTS (SELECT 1
		FROM DELETED D
		WHERE NOT EXISTS (SELECT 1
			FROM CTHD CT
			WHERE CT.SOHD = D.SOHD))
	BEGIN
		RAISERROR('Mỗi một hóa đơn phải có ít nhất một chi tiết hóa đơn.', 16, 1)
		ROLLBACK TRANSACTION
	END
END

-- I.14
GO
CREATE TRIGGER INSERT_UPDATE_HOADON
ON HOADON
AFTER INSERT, UPDATE
AS
BEGIN
	IF NOT UPDATE(TRIGIA)
		RETURN
	IF EXISTS (SELECT 1
		FROM INSERTED I
		WHERE I.TRIGIA != ISNULL((SELECT SUM(CT.SL * SP.GIA) 
			FROM CTHD CT
			JOIN SANPHAM SP ON CT.MASP = SP.MASP
			WHERE CT.SOHD = I.SOHD), 0))
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR (N'Trị giá của một hóa đơn là tổng thành tiền (số lượng * đơn giá) của các chi tiết thuộc hóa đơn đó.', 16, 1)
	END
END

GO
CREATE TRIGGER INSERT_UPDATE_DELETE_CTHD
ON CTHD
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @DS_SOHD TABLE (SOHD VARCHAR(10))
	INSERT INTO @DS_SOHD
	SELECT SOHD FROM INSERTED
	UNION
	SELECT SOHD FROM DELETED
	IF EXISTS (SELECT 1
		FROM HOADON HD
		JOIN @DS_SOHD DS ON HD.SOHD = DS.SOHD 
		WHERE HD.TRIGIA != ISNULL((SELECT SUM(CT.SL * SP.GIA) 
			FROM CTHD CT
			JOIN SANPHAM SP ON CT.MASP = SP.MASP
			WHERE CT.SOHD = HD.SOHD), 0))
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR (N'Trị giá của một hóa đơn là tổng thành tiền (số lượng * đơn giá) của các chi tiết thuộc hóa đơn đó.', 16, 1)
	END
END

GO
CREATE TRIGGER UPDATE_SANPHAM
ON SANPHAM
AFTER UPDATE
AS
BEGIN
	IF NOT UPDATE(GIA)
		RETURN
	IF EXISTS (
		SELECT 1
		FROM HOADON HD
		WHERE EXISTS (SELECT 1 
			FROM CTHD T 
			JOIN INSERTED I ON T.MASP = I.MASP 
			WHERE T.SOHD = HD.SOHD)
			AND HD.TRIGIA != ISNULL(( 
				SELECT SUM(CT.SL * SP.GIA) 
				FROM CTHD CT
				JOIN SANPHAM SP ON CT.MASP = SP.MASP
				WHERE CT.SOHD = HD.SOHD), 0))
	BEGIN
		ROLLBACK TRANSACTION
		RAISERROR (N'Trị giá của một hóa đơn là tổng thành tiền (số lượng * đơn giá) của các chi tiết thuộc hóa đơn đó.', 16, 1)
	END
END

-- I.15
GO
CREATE TRIGGER INSERT_UPDATE_KHACHHANG
ON KHACHHANG
AFTER INSERT,UPDATE
AS
BEGIN
	IF NOT(UPDATE(DOANHSO))
		RETURN
	IF EXISTS
	(
		SELECT I.MAKH
		FROM INSERTED I
		LEFT JOIN HOADON HD ON HD.MAKH = I.MAKH
		GROUP BY I.MAKH,I.DOANHSO
		HAVING DOANHSO != ISNULL(SUM(HD.TRIGIA), 0)
	)
	BEGIN
		RAISERROR('Doanh số của một khách hàng là tổng trị giá các hóa đơn mà khách hàng thành viên đó đã mua.',16,1)
		ROLLBACK TRANSACTION
	END
END

GO
CREATE TRIGGER INSERT_UPDATE_HOADON
ON HOADON
AFTER INSERT,UPDATE
AS
BEGIN
	IF NOT(UPDATE(MAKH) OR UPDATE(TRIGIA))
		RETURN
	IF EXISTS
	(
		SELECT KH.MAKH
		FROM KHACHHANG KH
		LEFT JOIN HOADON HD ON HD.MAKH = KH.MAKH
		WHERE KH.MAKH IN (SELECT DISTINCT MAKH FROM INSERTED)
		GROUP BY KH.MAKH, KH.DOANHSO
		HAVING DOANHSO != ISNULL(SUM(HD.TRIGIA), 0)
	)
	BEGIN
		RAISERROR('Doanh số của một khách hàng là tổng trị giá các hóa đơn mà khách hàng thành viên đó đã mua.',16,1)
		ROLLBACK TRANSACTION
	END
END

GO
CREATE TRIGGER DELETE_HOADON
ON HOADON
AFTER DELETE
AS
BEGIN
	IF EXISTS
	(
	SELECT KH.MAKH
	FROM KHACHHANG KH 
	LEFT JOIN HOADON HD ON KH.MAKH = HD.MAKH
	WHERE KH.MAKH IN (SELECT DISTINCT MAKH FROM DELETED)
	GROUP BY KH.MAKH,KH.DOANHSO
	HAVING DOANHSO != ISNULL(SUM(HD.TRIGIA), 0)
	)
	BEGIN
		RAISERROR('Doanh số của một khách hàng là tổng trị giá các hóa đơn mà khách hàng thành viên đó đã mua.',16,1)
		ROLLBACK TRANSACTION
	END
END

-- II.5
UPDATE KHACHHANG1
SET LOAIKH = 'Vip'
WHERE (NGDK < '2007-01-01' AND DOANHSO >= 10000000)
OR (NGDK >= '2007-01-01' AND DOANHSO >= 2000000)

-- III.8
SELECT KH.MAKH, KH.HOTEN
FROM KHACHHANG KH 
JOIN HOADON HD ON HD.MAKH = KH.MAKH
WHERE HD.NGHD = '2007-01-01'

-- III.9
SELECT HD.SOHD, HD.TRIGIA
FROM HOADON HD
JOIN NHANVIEN NV ON HD.MANV = NV.MANV
WHERE NV.HOTEN = 'Nguyen Van B'
AND NGHD = '2006-10-28'

-- III.10
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
JOIN CTHD CT ON CT.MASP = SP.MASP
JOIN HOADON HD ON HD.SOHD = CT.SOHD
JOIN KHACHHANG KH ON HD.MAKH = KH.MAKH
WHERE KH.HOTEN = 'Nguyen Van A'
AND MONTH(HD.NGHD) = 10 
AND YEAR(HD.NGHD) = 2006

-- III.11
SELECT CT.SOHD 
FROM CTHD CT
WHERE CT.MASP = 'BB01'
OR CT.MASP = 'BB02'

-- III.12
SELECT CT.SOHD 
FROM CTHD CT
WHERE (CT.MASP = 'BB01'
OR CT.MASP = 'BB02')
AND CT.SL BETWEEN 10 AND 20

-- III.13
SELECT CT.SOHD 
FROM CTHD CT
WHERE CT.MASP = 'BB01'
AND CT.SL BETWEEN 10 AND 20
INTERSECT
SELECT CT.SOHD 
FROM CTHD CT
WHERE CT.MASP = 'BB02'
AND CT.SL BETWEEN 10 AND 20

-- III.14
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
JOIN CTHD CT ON SP.MASP = CT.MASP
JOIN HOADON HD ON HD.SOHD = CT.SOHD
WHERE SP.NUOCSX = N'Trung Quoc' 
OR HD.NGHD = '2007-01-01'

-- III.15
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
EXCEPT
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
JOIN CTHD CT ON SP.MASP = CT.MASP

-- III.16
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
EXCEPT
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
JOIN CTHD CT ON SP.MASP = CT.MASP
JOIN HOADON HD ON HD.SOHD = CT.SOHD
WHERE YEAR(HD.NGHD) = 2006

-- III.17
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
WHERE SP.NUOCSX = 'Trung Quoc'
EXCEPT
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
JOIN CTHD CT ON SP.MASP = CT.MASP
JOIN HOADON HD ON HD.SOHD = CT.SOHD
WHERE YEAR(HD.NGHD) = 2006
AND SP.NUOCSX = 'Trung Quoc'

-- III.18
SELECT CT.SOHD
FROM CTHD CT
JOIN SANPHAM SP ON CT.MASP = SP.MASP
WHERE SP.NUOCSX = 'Singapore'
GROUP BY CT.SOHD
HAVING COUNT(DISTINCT SP.MASP) = (SELECT COUNT(*)
	FROM SANPHAM 
	WHERE NUOCSX = 'Singapore')

-- III.19
SELECT CT.SOHD
FROM CTHD CT
JOIN HOADON HD ON HD.SOHD = CT.SOHD
JOIN SANPHAM SP ON CT.MASP = SP.MASP
WHERE SP.NUOCSX = 'Singapore'
AND YEAR(HD.NGHD) = 2006
GROUP BY CT.SOHD
HAVING COUNT(DISTINCT SP.MASP) = (SELECT COUNT(*)
	FROM SANPHAM 
	WHERE NUOCSX = 'Singapore')

-- III.20
SELECT COUNT(SOHD) FROM HOADON WHERE MAKH IS NULL

-- III.21
SELECT DISTINCT SP.MASP, SP.TENSP
FROM SANPHAM SP
JOIN CTHD CT ON CT.MASP = SP.MASP
JOIN HOADON HD ON CT.SOHD = HD.SOHD
WHERE YEAR(HD.NGHD) = 2006

-- III.22
SELECT MAX(HD.TRIGIA) AS TRIGIACAONHAT, MIN(HD.TRIGIA) AS TRIGIATHAPNHAT
FROM HOADON HD

-- III.23
SELECT AVG(HD.TRIGIA) AS TRIGIATRUNGBINH
FROM HOADON HD
WHERE YEAR(HD.NGHD) = 2006

-- III.24
SELECT SUM(TRIGIA) AS TongDoanhThu2006
FROM HOADON
WHERE YEAR(NGHD) = 2006;

-- III.25
SELECT HD.SOHD
FROM HOADON HD
WHERE YEAR(HD.NGHD) = 2006
AND HD.TRIGIA = (SELECT MAX(TRIGIA)	
	FROM HOADON
	WHERE YEAR(NGHD) = 2006)

-- III.26
SELECT KH.HOTEN
FROM KHACHHANG KH
JOIN HOADON HD ON KH.MAKH = HD.MAKH
WHERE YEAR(HD.NGHD) = 2006
AND HD.TRIGIA = (SELECT MAX(TRIGIA)	
	FROM HOADON
	WHERE YEAR(NGHD) = 2006)

-- III.27
SELECT TOP(3) KH.MAKH, KH.HOTEN
FROM KHACHHANG KH
ORDER BY KH.DOANHSO DESC

-- III.28
WITH BAMUCGIACAONHAT AS (
	SELECT TOP(3) GIA 
	FROM SANPHAM
	ORDER BY GIA DESC)
SELECT SP.MASP, SP.TENSP 
FROM SANPHAM SP
WHERE SP.GIA IN (SELECT GIA FROM BAMUCGIACAONHAT)

-- III.29
WITH BAMUCGIACAONHAT AS (
	SELECT TOP(3) GIA 
	FROM SANPHAM
	ORDER BY GIA DESC)
SELECT SP.MASP, SP.TENSP 
FROM SANPHAM SP
WHERE SP.NUOCSX = 'Thai Lan'
AND SP.GIA IN (SELECT GIA FROM BAMUCGIACAONHAT)

-- III.30
WITH BAMUCGIACAONHAT AS (
	SELECT TOP(3) GIA 
	FROM SANPHAM
	WHERE NUOCSX = 'Trung Quoc'
	ORDER BY GIA DESC)
SELECT SP.MASP, SP.TENSP 
FROM SANPHAM SP
WHERE SP.NUOCSX = 'Trung Quoc'
AND SP.GIA IN (SELECT GIA FROM BAMUCGIACAONHAT)

-- III.31
WITH TOP3DOANHSO AS (SELECT TOP(3) KH.DOANHSO
	FROM KHACHHANG KH
	ORDER BY KH.DOANHSO DESC)
SELECT * 
FROM KHACHHANG KH 
WHERE KH.DOANHSO IN (SELECT DOANHSO FROM TOP3DOANHSO)

-- III.32
SELECT COUNT(MASP) AS TONGSOSANPHAMTQ 
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'

-- III.33
SELECT NUOCSX, COUNT(MASP) AS TONGSANPHAM
FROM SANPHAM
GROUP BY NUOCSX

-- III.34
SELECT NUOCSX, MAX(GIA) AS MAXGIA, MIN(GIA) AS MINGIA, AVG(GIA) AS TBGIA
FROM SANPHAM
GROUP BY NUOCSX

-- III.35
SELECT NGHD, SUM(TRIGIA) AS DOANHTHU
FROM HOADON
GROUP BY NGHD

-- III.36
SELECT MASP, SUM(SL)
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE MONTH(NGHD) = 10
AND YEAR(NGHD) = 2006
GROUP BY MASP

-- III.37
SELECT MONTH(NGHD), SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)

-- III.38
SELECT SOHD
FROM CTHD 
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) >= 4

-- III.39
SELECT SOHD
FROM CTHD
JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE NUOCSX = 'Viet Nam'
GROUP BY SOHD
HAVING COUNT(DISTINCT SANPHAM.MASP) = 3

-- III.40
SELECT TOP 1 WITH TIES KHACHHANG.MAKH, HOTEN
FROM KHACHHANG 
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
HAVING COUNT(HOADON.SOHD) = (SELECT TOP(1) COUNT(HD.SOHD) AS SOLAN
	FROM KHACHHANG KH
	JOIN HOADON HD ON KH.MAKH = HD.MAKH
	GROUP BY KH.MAKH, KH.HOTEN
	ORDER BY SOLAN DESC)

-- III.41
SELECT TOP(1) MONTH(NGHD), SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY DOANHTHU DESC

-- III.42
SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP 
JOIN CTHD CT ON CT.MASP = SP.MASP
JOIN HOADON HD ON HD.SOHD = CT.SOHD
WHERE YEAR(NGHD) = 2006
GROUP BY SP.MASP, SP.TENSP
HAVING SUM(CT.SL) = (SELECT TOP(1) SUM(SL) AS TONGSOLUONG
	FROM CTHD
	GROUP BY MASP
	ORDER BY TONGSOLUONG)

-- III.43
WITH GIABANCAONHATTHEONUOC AS (SELECT NUOCSX, MAX(GIA) AS MAXGIA
	FROM SANPHAM
	GROUP BY NUOCSX)
SELECT MASP, TENSP
FROM SANPHAM SP
JOIN GIABANCAONHATTHEONUOC GB ON SP.NUOCSX = GB.NUOCSX
AND SP.GIA = GB.MAXGIA

-- III.44
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3;

-- III.45
WITH Top10MAKH AS (
    SELECT TOP 10 WITH TIES MAKH
    FROM KHACHHANG
    ORDER BY DOANHSO DESC
),
KhachHangMuaNhieuNhatTrongTop10 AS (
    SELECT T1.MAKH, KH.HOTEN, KH.DOANHSO, COUNT(T1.SOHD) AS SoLanMuaHang
    FROM HOADON T1
    JOIN KHACHHANG KH ON T1.MAKH = KH.MAKH
    WHERE T1.MAKH IN (SELECT MAKH FROM Top10MAKH) 
    GROUP BY T1.MAKH, KH.HOTEN, KH.DOANHSO
)
SELECT TOP 1 WITH TIES MAKH, HOTEN, DOANHSO, SoLanMuaHang
FROM KhachHangMuaNhieuNhatTrongTop10
ORDER BY SoLanMuaHang DESC;