-- 24520602 -- Nguyễn Duy Hưng

USE QlyHangHoa;

-- Câu 1
SELECT MANCC, TENNCC, THANHPHO FROM NHACUNGCAP;

-- Câu 2
SELECT * FROM PHUTUNG;

-- Câu 3
SELECT * FROM NHACUNGCAP WHERE THANHPHO = N'London';

-- Câu 4
SELECT MAPT, TENPT, MAUSAC FROM PHUTUNG WHERE THANHPHO = N'Paris'

-- Câu 5
SELECT MAPT, TENPT, KHOILUONG FROM PHUTUNG WHERE KHOILUONG > 15;

-- Câu 6
(SELECT MAPT, TENPT, KHOILUONG FROM PHUTUNG WHERE KHOILUONG > 15)
EXCEPT
(SELECT MAPT, TENPT, KHOILUONG FROM PHUTUNG WHERE KHOILUONG > 15 AND MAUSAC = 'red');

-- Câu 7
(SELECT MAPT, TENPT, KHOILUONG FROM PHUTUNG WHERE KHOILUONG > 15)
EXCEPT
(SELECT MAPT, TENPT, KHOILUONG FROM PHUTUNG WHERE KHOILUONG > 15 AND (MAUSAC = 'red' OR MAUSAC = 'green'));

-- Câu 8
SELECT MAPT, TENPT, KHOILUONG FROM PHUTUNG WHERE KHOILUONG > 15 AND KHOILUONG < 20
ORDER BY TENPT;

-- Câu 9
SELECT DISTINCT PHUTUNG.MAPT, TENPT, MAUSAC, KHOILUONG, THANHPHO FROM PHUTUNG 
JOIN VANCHUYEN ON PHUTUNG.MAPT = VANCHUYEN.MAPT 
WHERE VANCHUYEN.MANCC = 'S1';

-- Câu 10
SELECT DISTINCT NHACUNGCAP.MANCC, TENNCC, TRANGTHAI, THANHPHO FROM NHACUNGCAP 
JOIN VANCHUYEN ON NHACUNGCAP.MANCC = VANCHUYEN.MANCC 
WHERE MAPT = 'P1';

-- Câu 11
SELECT DISTINCT NHACUNGCAP.MANCC, TENNCC, TRANGTHAI, NHACUNGCAP.THANHPHO FROM NHACUNGCAP 
JOIN VANCHUYEN ON NHACUNGCAP.MANCC = VANCHUYEN.MANCC 
JOIN PHUTUNG ON VANCHUYEN.MAPT = PHUTUNG.MAPT
WHERE NHACUNGCAP.THANHPHO = 'London' AND PHUTUNG.THANHPHO = 'London';

-- Câu 12
SELECT DISTINCT PHUTUNG.MAPT, TENPT, MAUSAC, KHOILUONG, THANHPHO FROM PHUTUNG 
WHERE MAPT IN (SELECT MAPT FROM VANCHUYEN WHERE MANCC = 'S1') ;

-- Câu 13
SELECT DISTINCT NHACUNGCAP.MANCC, TENNCC, TRANGTHAI, THANHPHO FROM NHACUNGCAP 
WHERE MANCC IN (SELECT MANCC FROM VANCHUYEN WHERE MAPT = 'P1');

-- Câu 14
SELECT DISTINCT PHUTUNG.MAPT, TENPT, MAUSAC, KHOILUONG, THANHPHO FROM PHUTUNG  
WHERE EXISTS(SELECT 1 FROM VANCHUYEN WHERE VANCHUYEN.MAPT = PHUTUNG.MAPT AND VANCHUYEN.MANCC = 'S1');

-- Câu 15
SELECT DISTINCT NHACUNGCAP.MANCC, TENNCC, TRANGTHAI, THANHPHO FROM NHACUNGCAP 
WHERE EXISTS(SELECT 1 FROM VANCHUYEN WHERE VANCHUYEN.MANCC = NHACUNGCAP.MANCC AND VANCHUYEN.MAPT = 'P1');

-- Câu 16
SELECT DISTINCT MANCC, TENNCC, TRANGTHAI, THANHPHO
FROM NHACUNGCAP
WHERE THANHPHO = 'London'AND MANCC 
IN (SELECT MANCC FROM VANCHUYEN WHERE MAPT 
IN (SELECT MAPT FROM PHUTUNG WHERE THANHPHO = 'London'));

-- Câu 17
SELECT DISTINCT MANCC, TENNCC, TRANGTHAI, THANHPHO
FROM NHACUNGCAP WHERE THANHPHO = 'London' AND 
EXISTS(SELECT 1 FROM VANCHUYEN WHERE VANCHUYEN.MANCC = NHACUNGCAP.MANCC AND 
EXISTS(SELECT 1 FROM PHUTUNG WHERE THANHPHO = 'London' AND PHUTUNG.MAPT = VANCHUYEN.MAPT));   

-- Câu 18
SELECT DISTINCT MANCC, TENNCC, TRANGTHAI, THANHPHO
FROM NHACUNGCAP
WHERE MANCC NOT IN (SELECT MANCC FROM VANCHUYEN);

-- Câu 19
SELECT DISTINCT MANCC, TENNCC, TRANGTHAI, THANHPHO
FROM NHACUNGCAP
WHERE EXISTS (SELECT 1 FROM VANCHUYEN WHERE VANCHUYEN.MANCC = NHACUNGCAP.MANCC);

-- Câu 20
SELECT DISTINCT NHACUNGCAP.MANCC, TENNCC, TRANGTHAI, THANHPHO
FROM NHACUNGCAP LEFT JOIN VANCHUYEN ON VANCHUYEN.MANCC = NHACUNGCAP.MANCC WHERE VANCHUYEN.MANCC IS NULL;

-- Câu 21
SELECT COUNT(*) AS SONHACUNGCAP FROM NHACUNGCAP;

-- Câu 22
SELECT COUNT(*) AS SONHACUNGCAP FROM NHACUNGCAP WHERE THANHPHO = 'London';

-- Câu 23
SELECT MAX(TRANGTHAI) AS GIATRICAONHAT, MIN(TRANGTHAI) AS GIATRITHAPNHAT FROM NHACUNGCAP;

-- Câu 24
SELECT MAX(TRANGTHAI) AS GIATRICAONHAT, MIN(TRANGTHAI) AS GIATRITHAPNHAT FROM NHACUNGCAP WHERE THANHPHO = 'London';

-- Câu 25
SELECT NHACUNGCAP.MANCC, COUNT(MAPT) AS TONGSOPHUTUNG FROM NHACUNGCAP 
LEFT JOIN VANCHUYEN ON NHACUNGCAP.MANCC = VANCHUYEN.MANCC 
GROUP BY NHACUNGCAP.MANCC;

-- Câu 26
SELECT NHACUNGCAP.MANCC, TENNCC, THANHPHO, COUNT(MAPT) AS TONGSOPHUTUNG FROM NHACUNGCAP 
LEFT JOIN VANCHUYEN ON NHACUNGCAP.MANCC = VANCHUYEN.MANCC 
GROUP BY NHACUNGCAP.MANCC, TENNCC, THANHPHO;

-- Câu 27
SELECT MANCC FROM VANCHUYEN
GROUP BY MANCC
HAVING COUNT(MAPT) > 500;

-- Câu 28
SELECT MANCC FROM VANCHUYEN
JOIN PHUTUNG ON VANCHUYEN.MAPT = PHUTUNG.MAPT
WHERE MAUSAC = N'màu đỏ'
GROUP BY MANCC
HAVING COUNT(PHUTUNG.MAPT) > 300; 

-- Câu 29
SELECT NHACUNGCAP.MANCC, TENNCC, NHACUNGCAP.THANHPHO, COUNT(PHUTUNG.MAPT) AS SOLUONGPHUTUNGMAUDO FROM NHACUNGCAP 
JOIN VANCHUYEN ON NHACUNGCAP.MANCC = VANCHUYEN.MANCC
JOIN PHUTUNG ON VANCHUYEN.MAPT = PHUTUNG.MAPT
WHERE MAUSAC = N'màu đỏ'
GROUP BY NHACUNGCAP.MANCC, TENNCC, NHACUNGCAP.THANHPHO
HAVING COUNT(PHUTUNG.MAPT) > 300;

-- Câu 30
SELECT THANHPHO, COUNT(MANCC) FROM NHACUNGCAP GROUP BY THANHPHO;

-- Câu 31
SELECT TOP(1) NHACUNGCAP.MANCC, COUNT(MAPT) AS TONGSOPHUTUNG FROM NHACUNGCAP 
LEFT JOIN VANCHUYEN ON NHACUNGCAP.MANCC = VANCHUYEN.MANCC 
GROUP BY NHACUNGCAP.MANCC;

-- Câu 32
SELECT NHACUNGCAP.THANHPHO FROM NHACUNGCAP 
JOIN VANCHUYEN ON NHACUNGCAP.MANCC = VANCHUYEN.MANCC
JOIN PHUTUNG ON NHACUNGCAP.THANHPHO = PHUTUNG.THANHPHO
GROUP BY NHACUNGCAP.THANHPHO;

-- Câu 33
INSERT INTO NHACUNGCAP (MANCC, TENNCC, TRANGTHAI, THANHPHO) VALUES ('S6', 'Duncan', 30, 'Paris');  

-- Câu 34
UPDATE NHACUNGCAP SET THANHPHO = 'Sydney' WHERE MANCC = 'S6';

-- Câu 35
UPDATE NHACUNGCAP SET TRANGTHAI = TRANGTHAI + 10 WHERE THANHPHO = 'London';

-- Câu 36
DELETE FROM NHACUNGCAP WHERE MANCC = 'S6'