-- 24520602 -- Nguyễn Duy Hưng

USE QlyCuaHangHoa

-- Đề I 

-- 2.e
SELECT 
    NGAYBAN, 
    COUNT(DISTINCT DONHANG.MADH) AS SoDonHangDaGiao
FROM 
    CTDH 
    JOIN DONHANG ON CTDH.MADH = DONHANG.MADH
    JOIN GIAOHANG ON DONHANG.MADH = GIAOHANG.MADH
WHERE 
    MASP = 'HOABO01'
    AND MONTH(NGAYBAN) = 10
    AND YEAR(NGAYBAN) = 2023
    AND DAGIAO = 1
GROUP BY 
    NGAYBAN
ORDER BY 
    NGAYBAN

-- 2.f
SELECT 
    NGGIAO, DT_NGGIAO
FROM 
    CTDH 
    JOIN GIAOHANG ON GIAOHANG.MADH = CTDH.MADH
    JOIN SANPHAM ON CTDH.MASP = SANPHAM.MASP
WHERE 
    DAGIAO = 1 AND GIABAN >= 1000000
GROUP BY 
    NGGIAO, DT_NGGIAO
HAVING 
    COUNT(DISTINCT SANPHAM.MASP) = (SELECT COUNT(DISTINCT MASP) FROM SANPHAM WHERE GIABAN >= 1000000)

-- Đề II

-- 2.e
SELECT 
    SANPHAM.MASP, SUM(SOLUONG) AS TongSoLuong
FROM 
    CTDH 
    JOIN DONHANG ON DONHANG.MADH = CTDH.MADH
    JOIN SANPHAM ON CTDH.MASP = SANPHAM.MASP
WHERE 
    MANY = 'NV01' AND MONTH(NGAYBAN) = 10 AND YEAR(NGAYBAN) = 2023
GROUP BY 
    SANPHAM.MASP

-- 2.f
SELECT 
    NGGIAO, DT_NGGIAO
FROM 
    CTDH 
    JOIN GIAOHANG ON GIAOHANG.MADH = CTDH.MADH
    JOIN SANPHAM ON CTDH.MASP = SANPHAM.MASP
WHERE 
    DAGIAO = 1 AND THELOAI = N'hoa nhập khẩu'
GROUP BY 
    NGGIAO, DT_NGGIAO
HAVING 
    COUNT(DISTINCT SANPHAM.MASP) = (SELECT COUNT(DISTINCT MASP) FROM SANPHAM WHERE THELOAI = N'hoa nhập khẩu')